const val DEPS_FILE_NAME = "deps.json"
const val CLI_VERSION_JSON_ATTRIBUTE_NAME = "cliVersion"
const val LANG_VERSION_JSON_ATTRIBUTE_NAME = "cliVersion"
const val SOURCE_DIR_NAME = "src"
const val MAIN_SOURCE_FILE_NAME = "main"
const val BINARY_DIR_NAME = "bin"
const val CLASSES_DIR_NAME = "bin"
